[package]
name = "PrettyPrintcess"
version = "0.1.0"
edition = "2024"

[dependencies]
cidr = "0.3.1"
futures = "0.3.31"
get_if_addrs = "0.5.3"
local-ip-address = "0.6.5"
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "net", "time", "io-util"] }
